function myFunction(){

alert("You awake to the terrifying screach. High pitched and banshee-like it reverbarates accross the valley. You peer cautiously from the window. You have heard that piercing sound countless times before, but it still send an icy shiver through your body. The call of the raptor will terrify even the bravest of souls. It had been 2 years since the Blunder. The first cloned raptors we're a miricle of modern science. They were allowed to roam in a park, a Jurrasic Park. No one knew that their drinking creek had been contaminated by the toxic runoff of the local Smart Drug company... On the moonlit hill above you spot the hunting party moving quickly towards the town.")
  var answer = prompt("You need to prepare for the attack. You...  (a)Gather Weapons, lots of them. (b)Sound the alarm, you're gonna need back up. (C)Roll up those sleeves, and walk outside. This is what you've been training for...")

if(answer === "a"){var answerTwo = prompt("You dash down the stairs. Frantically, you open drawers and cupboards looking for your trusty weapon. Where could it be? You hear the echo of raptor claws tapping on city streets. You lift up a newspaper and see your trusty slingshot! You have been practicing hitting cans, and you are a deadshot. You got this... Do you (a)Attack or (b)Runaway?")}
  if(answerTwo === "a"){alert("Did you truly believe you could take down a group of highly intelligent raptors with a slingshot? You become dinner. YOU HAVE LOST")}
  //if(answerTwo === "b"){alert("You run away to safety")}

if(answer === "b" || answerTwo === "b"){var answerThree = prompt("You dart through an open window, an slip away into the darkness... You know that most people in the town have been devoured or imprisoned, but there is a stronghold of strongmen to the South (they are mean, but surely they could take the raptors right?), and to the north of you there lies the old orphanage (shouldn't someone should warn them about the impending raid?) do you go (South) or (North)?")}
  if(answerThree === "South"){alert("The strongmen had a bad rep amongst the townsfolk, so one can only imagine the disdain the raptors had for them, by the time you arrive their compound has already been decimated, you can see smoke starting to loom from the orphanage in the North. You sit upon the ground, defeated, crushed by your feelings of guilt. YOU HAVE LOST")}
  if(answerThree === "North"){var answerFour = prompt("You make your way swiftly up the road. The wind is howling. You run as fast as you can, your lungs struggle taking in the cold night air. As you near the old orphanage, you see the raptors making their way stealthly up the other side of the hill. 'The Raptors are coming!' you yell. The alarm bell is sounded, and the orphans begin manning their battle stations. You need to stall the raptors, to buy them more time. Do you: (a) Do a super intense coreographed dance. (b) Use your magic?")}
    if (answerFour === "a"){alert("You close your eyes and summon your inner MJ. You dance with everything you've got. Hands and feet moving like whilwinds. Moonwalk, roger-rabbit, running man. You work your way through your extensive repetoire of sweet moves. You begin to moonwalk, and as you end the end of known dance moves in your dance move arsenal you gear up for on final spinning jump. It all comes down to this. With a full force hop, skip, and a jump you launch yourself into the air. Time moves in slow motion. You feell your body twist. Front flip. Then another. Then ANOTHER. You are spin gracefully through the air, you see the raptors looking eagerly at you, ready to pounce. As you touch down, the orphans launch their nets into the air. The raptors are ensnared. 'Nailed it.' you say, and stroll off into the sunset, leather jacket in hand. YOU HAVE SAVED THE DAY.")}
    if (answerFour === "b"){alert("You put on your power glove, and prepare to get down to business. Since the raptor invasion, you have only one DVD. 'David Blaine's How to Do Magic Good and Stuff'. You pull out your cards and ready your trick. No one is impressed. Not even the orphans. You are terrible at magic, and terribly delicious to the raptors. YOU HAVE LOST.")}
if(answer === "c"){var answerFive= prompt("The raptors are nearing the town, but you still have time for a montage. You do pushups. One handed pushups. You punch bricks. You break boards. You practice karate. You have LEVELED UP! You hear the raptors outside. Time to do this. You step outside, and find yourself face to face with the dinosaur cohort. Do you use: (K) Karate or (O)Your Ocarina?")}
  if(answerFive === "o"){alert("You spin the ocarina out of your pocket with pizzaz, and crouch in playing position, Alright! You begin to play, the most beautiful ocarina music. It's beautiful, the raptors begin to cry. The birds in the sky begin to cry. As the music echoes through the valley, everyone and everything that hears it also begins to cry. You change keys, it's really powerful. The raptors are entranced. You have successfully hypnotized them. With a front flip, you land upon the lead raptor. You ride your new raptor off into the night, followed by the rest... in an awesome flying-V formation. YOU HAVE WON")}
  if(answerFive === "k"){var answerSix= prompt("You square up with the raptors. One lunges at you with its claws. You DODGE, but a claw scrapes your forehead. You rip off your sleeve and tie it around your head. 'Let's do this...' you mutter. You get ready to use KARATE. (Pick a number between 1 and 10)")}
    if (answerSix <= 5){alert("You perform a spinning whirlwind kick so fast, that you create a mini-tornado. The raptors are sucked into the sky, and fall to the earth defeated. YOU HAVE LIVED TO SEE ANOTHER DAY.")}
    if (answerSix > 5){alert("You perform a flying bicycle kick, but it was poorly calculated. Your leg enters directly into the jaws of a hungry raptor. *The Horror* YOU HAVE LOST.")}
}
object.onclick=myFunction();
